DO $$
BEGIN
	IF EXISTS (
		SELECT 1 FROM "model_policies"
		WHERE "economy_model_definition_id" IN ('MODEL-OPENAI-GPT-5-6-LUNA', 'MODEL-OPENAI-GPT-5-6-TERRA', 'MODEL-OPENAI-GPT-5-6-SOL', 'MODEL-GROQ-GPT-OSS-20B', 'MODEL-GROQ-GPT-OSS-120B')
			OR "balanced_model_definition_id" IN ('MODEL-OPENAI-GPT-5-6-LUNA', 'MODEL-OPENAI-GPT-5-6-TERRA', 'MODEL-OPENAI-GPT-5-6-SOL', 'MODEL-GROQ-GPT-OSS-20B', 'MODEL-GROQ-GPT-OSS-120B')
			OR "best_model_definition_id" IN ('MODEL-OPENAI-GPT-5-6-LUNA', 'MODEL-OPENAI-GPT-5-6-TERRA', 'MODEL-OPENAI-GPT-5-6-SOL', 'MODEL-GROQ-GPT-OSS-20B', 'MODEL-GROQ-GPT-OSS-120B')
	) OR EXISTS (
		SELECT 1 FROM "agent_runs"
		WHERE "model_definition_id" IN ('MODEL-OPENAI-GPT-5-6-LUNA', 'MODEL-OPENAI-GPT-5-6-TERRA', 'MODEL-OPENAI-GPT-5-6-SOL', 'MODEL-GROQ-GPT-OSS-20B', 'MODEL-GROQ-GPT-OSS-120B')
	) OR EXISTS (
		SELECT 1 FROM "model_calls"
		WHERE "model_definition_id" IN ('MODEL-OPENAI-GPT-5-6-LUNA', 'MODEL-OPENAI-GPT-5-6-TERRA', 'MODEL-OPENAI-GPT-5-6-SOL', 'MODEL-GROQ-GPT-OSS-20B', 'MODEL-GROQ-GPT-OSS-120B')
	) THEN
		RAISE EXCEPTION 'Cannot roll back hosted model candidates while policy or run evidence references them';
	END IF;
END $$;
--> statement-breakpoint
DELETE FROM "model_definitions"
WHERE "id" IN ('MODEL-OPENAI-GPT-5-6-LUNA', 'MODEL-OPENAI-GPT-5-6-TERRA', 'MODEL-OPENAI-GPT-5-6-SOL', 'MODEL-GROQ-GPT-OSS-20B', 'MODEL-GROQ-GPT-OSS-120B');
