import type { OrganizationRole } from '../identity.schema';

export const ORGANIZATION_READ = 'organization:read' as const;
export const MEMBER_READ = 'member:read' as const;
export const INVITATION_MANAGE = 'invitation:manage' as const;
export const PROJECT_READ = 'project:read' as const;
export const PROJECT_CREATE = 'project:create' as const;
export const PROJECT_ARCHIVE = 'project:archive' as const;
export const PROJECT_RESTORE = 'project:restore' as const;
export const CLARIFICATION_ANSWER = 'clarification:answer' as const;
export const ARTIFACT_GENERATE = 'artifact:generate' as const;
export const ARTIFACT_APPROVE = 'artifact:approve' as const;
export const ARCHITECTURE_GENERATE = 'architecture:generate' as const;
export const ARCHITECTURE_APPROVE = 'architecture:approve' as const;
export const EXPERIENCE_GENERATE = 'experience:generate' as const;
export const EXPERIENCE_REVIEW = 'experience:review' as const;
export const WORKSPACE_READ = 'workspace:read' as const;
export const WORK_ITEM_READ = 'work-item:read' as const;
export const WORK_ITEM_GENERATE = 'work-item:generate' as const;
export const WORK_ITEM_REVIEW = 'work-item:review' as const;
export const ENGINEERING_PLAN_GENERATE = 'engineering-plan:generate' as const;
export const BILLING_READ = 'billing:read' as const;
export const BILLING_MANAGE = 'billing:manage' as const;
export const MODEL_CATALOG_READ = 'model-catalog:read' as const;
export const SOURCE_MANAGE = 'source:manage' as const;
export const ANALYSIS_RUN = 'analysis:run' as const;

export type Permission =
  | typeof ORGANIZATION_READ
  | typeof MEMBER_READ
  | typeof INVITATION_MANAGE
  | typeof PROJECT_READ
  | typeof PROJECT_CREATE
  | typeof PROJECT_ARCHIVE
  | typeof PROJECT_RESTORE
  | typeof CLARIFICATION_ANSWER
  | typeof ARTIFACT_GENERATE
  | typeof ARTIFACT_APPROVE
  | typeof ARCHITECTURE_GENERATE
  | typeof ARCHITECTURE_APPROVE
  | typeof EXPERIENCE_GENERATE
  | typeof EXPERIENCE_REVIEW
  | typeof WORKSPACE_READ
  | typeof WORK_ITEM_READ
  | typeof WORK_ITEM_GENERATE
  | typeof WORK_ITEM_REVIEW
  | typeof ENGINEERING_PLAN_GENERATE
  | typeof BILLING_READ
  | typeof BILLING_MANAGE
  | typeof MODEL_CATALOG_READ
  | typeof SOURCE_MANAGE
  | typeof ANALYSIS_RUN;

const ROLE_PERMISSIONS: Readonly<Record<OrganizationRole, ReadonlySet<Permission>>> = {
  OWNER: new Set([ORGANIZATION_READ, MEMBER_READ, INVITATION_MANAGE, PROJECT_READ, PROJECT_CREATE, PROJECT_ARCHIVE, PROJECT_RESTORE, CLARIFICATION_ANSWER, ARTIFACT_GENERATE, ARTIFACT_APPROVE, ARCHITECTURE_GENERATE, ARCHITECTURE_APPROVE, EXPERIENCE_GENERATE, EXPERIENCE_REVIEW, WORKSPACE_READ, WORK_ITEM_READ, WORK_ITEM_GENERATE, WORK_ITEM_REVIEW, ENGINEERING_PLAN_GENERATE, BILLING_READ, BILLING_MANAGE, MODEL_CATALOG_READ, SOURCE_MANAGE, ANALYSIS_RUN]),
  ADMINISTRATOR: new Set([ORGANIZATION_READ, MEMBER_READ, INVITATION_MANAGE, PROJECT_READ, PROJECT_CREATE, PROJECT_ARCHIVE, PROJECT_RESTORE, CLARIFICATION_ANSWER, ARTIFACT_GENERATE, ARTIFACT_APPROVE, ARCHITECTURE_GENERATE, ARCHITECTURE_APPROVE, EXPERIENCE_GENERATE, EXPERIENCE_REVIEW, WORKSPACE_READ, WORK_ITEM_READ, WORK_ITEM_GENERATE, WORK_ITEM_REVIEW, ENGINEERING_PLAN_GENERATE, BILLING_READ, BILLING_MANAGE, MODEL_CATALOG_READ, SOURCE_MANAGE, ANALYSIS_RUN]),
  PRODUCT_ANALYST: new Set([ORGANIZATION_READ, PROJECT_READ, PROJECT_CREATE, CLARIFICATION_ANSWER, ARTIFACT_GENERATE, ARTIFACT_APPROVE, ARCHITECTURE_GENERATE, EXPERIENCE_GENERATE, EXPERIENCE_REVIEW, WORKSPACE_READ, WORK_ITEM_READ, WORK_ITEM_GENERATE, WORK_ITEM_REVIEW, ENGINEERING_PLAN_GENERATE, MODEL_CATALOG_READ, SOURCE_MANAGE, ANALYSIS_RUN]),
  ARCHITECT: new Set([ORGANIZATION_READ, PROJECT_READ, PROJECT_CREATE, CLARIFICATION_ANSWER, ARTIFACT_GENERATE, ARTIFACT_APPROVE, ARCHITECTURE_GENERATE, ARCHITECTURE_APPROVE, EXPERIENCE_GENERATE, EXPERIENCE_REVIEW, WORKSPACE_READ, WORK_ITEM_READ, WORK_ITEM_GENERATE, WORK_ITEM_REVIEW, ENGINEERING_PLAN_GENERATE, MODEL_CATALOG_READ, SOURCE_MANAGE, ANALYSIS_RUN]),
  DEVELOPER: new Set([ORGANIZATION_READ, PROJECT_READ, WORKSPACE_READ, WORK_ITEM_READ, MODEL_CATALOG_READ]),
  REVIEWER: new Set([ORGANIZATION_READ, PROJECT_READ, EXPERIENCE_REVIEW, WORKSPACE_READ, WORK_ITEM_READ, WORK_ITEM_REVIEW, MODEL_CATALOG_READ]),
  VIEWER: new Set([ORGANIZATION_READ, PROJECT_READ, WORKSPACE_READ, WORK_ITEM_READ, MODEL_CATALOG_READ])
};

export function roleAllows(role: OrganizationRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].has(permission);
}
