export const OPENAI_GPT_5_6_LUNA_MODEL_DEFINITION_ID = 'MODEL-OPENAI-GPT-5-6-LUNA';
export const OPENAI_GPT_5_6_TERRA_MODEL_DEFINITION_ID = 'MODEL-OPENAI-GPT-5-6-TERRA';
export const OPENAI_GPT_5_6_SOL_MODEL_DEFINITION_ID = 'MODEL-OPENAI-GPT-5-6-SOL';
export const GROQ_GPT_OSS_20B_MODEL_DEFINITION_ID = 'MODEL-GROQ-GPT-OSS-20B';
export const GROQ_GPT_OSS_120B_MODEL_DEFINITION_ID = 'MODEL-GROQ-GPT-OSS-120B';

export const OPENAI_GPT_5_6_LUNA_MODEL_ID = 'gpt-5.6-luna';
export const OPENAI_GPT_5_6_TERRA_MODEL_ID = 'gpt-5.6-terra';
export const OPENAI_GPT_5_6_SOL_MODEL_ID = 'gpt-5.6-sol';
export const GROQ_GPT_OSS_20B_MODEL_ID = 'openai/gpt-oss-20b';
export const GROQ_GPT_OSS_120B_MODEL_ID = 'openai/gpt-oss-120b';
